-- Enable Row-Level Security on all tables
-- Prisma connects as the postgres superuser/service_role which bypasses RLS,
-- so all API access through Next.js continues to work normally.
-- This blocks direct PostgREST/anon access to all tables.

ALTER TABLE "User" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Profile" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Account" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Session" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "VerificationToken" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "MedicalDocument" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "LabValue" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "TrainingActivity" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "TrainingPlanEntry" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ManualTrainingEntry" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "StravaIntegration" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "TrainingPeaksIntegration" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "GarminIntegration" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "GarminDailyHealth" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "CoachAthlete" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "CoachNote" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "NutritionistClient" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "NutritionNote" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "FoodItem" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "DailyCheckin" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "DailyRecommendation" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "DailyFeedback" ENABLE ROW LEVEL SECURITY;
