services:
  postgres:
    image: postgres:16-alpine
    container_name: streho_postgres
    restart: always
    environment:
      POSTGRES_USER: streho_user
      POSTGRES_PASSWORD: streho_password
      POSTGRES_DB: streho_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: streho_app
    depends_on:
      - postgres
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://streho_user:streho_password@postgres:5432/streho_db
      NEXTAUTH_URL: http://localhost:3000
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      NODE_ENV: production

volumes:
  postgres_data:
