export type FoodMoment = 'preWorkout' | 'intraWorkout' | 'postWorkout' | 'snack' | 'dinner';

export type FoodOption = {
  name: string;
  description: string;
  moment: FoodMoment;
  focus: string[];
  carbs: number;
  protein: number;
  fat: number;
  kcal: number;
  portion: string;
};

const buildFood = (overrides: Partial<FoodOption> & Pick<FoodOption, 'name' | 'description' | 'moment' | 'focus'>): FoodOption => ({
  carbs: 35,
  protein: 12,
  fat: 6,
  kcal: 300,
  portion: '1 porción',
  ...overrides,
});

export const foodCatalog: FoodOption[] = [
  // ============================================================
  // PRE-WORKOUT (20 items)
  // ============================================================

  buildFood({
    name: 'Marraqueta + palta + huevo duro',
    description: 'Carbohidratos suaves y grasas chilenas para cargar antes de salir en rodados Z2.',
    moment: 'preWorkout',
    focus: ['energy availability', 'performance + recovery'],
    carbs: 45, protein: 14, fat: 15, kcal: 420,
    portion: '2 rebanadas de marraqueta + 1 palta y 1 huevo',
  }),
  buildFood({
    name: 'Barquete de avena con mote',
    description: 'Avena, mote y miel para mantener la energía en sesión larga. La avena aporta beta-glucano anti-inflamatorio.',
    moment: 'preWorkout',
    focus: ['energy availability', 'maintenance', 'recovery'],
    carbs: 62, protein: 10, fat: 5, kcal: 380,
    portion: '1 taza cocida',
  }),
  buildFood({
    name: 'Sándwich integral de ave y palta',
    description: 'Alternativa rápida para viaje en bici. Proteína magra y grasas saludables para performance.',
    moment: 'preWorkout',
    focus: ['energy availability', 'performance + recovery'],
    carbs: 48, protein: 22, fat: 14, kcal: 450,
    portion: '1 sándwich mediano',
  }),
  buildFood({
    name: 'Tostadas integrales con requesón y miel',
    description: 'Carbohidratos de digestión media con proteína láctea. Macros balanceados para sesiones moderadas.',
    moment: 'preWorkout',
    focus: ['energy availability', 'maintenance'],
    carbs: 38, protein: 10, fat: 4, kcal: 240,
    portion: '2 tostadas + 2 cdas requesón',
  }),
  buildFood({
    name: 'Plátano con mantequilla de maní',
    description: 'Carbohidratos rápidos y grasas para energía sostenida antes del entrenamiento.',
    moment: 'preWorkout',
    focus: ['energy availability'],
    carbs: 30, protein: 7, fat: 10, kcal: 240,
    portion: '1 plátano mediano + 1 cda mantequilla de maní',
  }),
  buildFood({
    name: 'Arroz con leche bajo en azúcar',
    description: 'Carbohidratos complejos con digestión suave, buena tolerancia gastrointestinal y calcio.',
    moment: 'preWorkout',
    focus: ['energy availability', 'maintenance', 'recovery'],
    carbs: 52, protein: 8, fat: 3, kcal: 280,
    portion: '1 taza (250 ml)',
  }),
  buildFood({
    name: 'Mote con huesillos (reducir syrup)',
    description: 'Clásico chileno: mote de trigo con frutas deshidratadas, carbohidratos lentos y sabor local.',
    moment: 'preWorkout',
    focus: ['energy availability'],
    carbs: 45, protein: 3, fat: 0, kcal: 200,
    portion: '1 taza mote + 3-4 huesillos',
  }),
  buildFood({
    name: 'Batido de plátano, avena y leche',
    description: 'Batido pre-entrenamiento con carbohidratos, proteína y energía para sesiones de alta carga.',
    moment: 'preWorkout',
    focus: ['energy availability', 'performance + recovery'],
    carbs: 55, protein: 12, fat: 5, kcal: 340,
    portion: '400 ml',
  }),
  buildFood({
    name: 'Yogurt griego con granola y miel',
    description: 'Proteína y carbohidratos de liberación gradual. Ratio CHO:PRO 2.7:1 para rendimiento y recuperación.',
    moment: 'preWorkout',
    focus: ['maintenance', 'recovery', 'performance + recovery'],
    carbs: 40, protein: 15, fat: 6, kcal: 320,
    portion: '200g yogurt + 3 cdas granola',
  }),
  buildFood({
    name: 'Pan de molde integral con pavo y tomate',
    description: 'Pre-entrenamiento ligero con proteína magra y carbohidratos para recuperación activa.',
    moment: 'preWorkout',
    focus: ['recovery'],
    carbs: 34, protein: 18, fat: 5, kcal: 280,
    portion: '2 rebanadas + 60g pavo',
  }),
  buildFood({
    name: 'Porridge de avena con higos y nueces',
    description: 'Avena cocida con higos secos y nueces: carbohidratos de absorción lenta y grasas saludables.',
    moment: 'preWorkout',
    focus: ['energy availability', 'performance + recovery'],
    carbs: 58, protein: 12, fat: 12, kcal: 390,
    portion: '1 taza cocida + 3 higos + 15g nueces',
  }),
  buildFood({
    name: 'Pan amasado con mantequilla y miel',
    description: 'Pan tradicional chileno con carbohidratos de fácil digestión para sesiones matutinas cortas.',
    moment: 'preWorkout',
    focus: ['energy availability', 'maintenance'],
    carbs: 50, protein: 6, fat: 10, kcal: 320,
    portion: '1 pan mediano + 1 cdita mantequilla + 1 cdita miel',
  }),
  buildFood({
    name: 'Batido de durazno, avena y leche descremada',
    description: 'Durazno fresco o en conserva con avena: fructosa + polisacáridos para energía sostenida.',
    moment: 'preWorkout',
    focus: ['energy availability', 'maintenance'],
    carbs: 52, protein: 12, fat: 3, kcal: 300,
    portion: '350 ml',
  }),
  buildFood({
    name: 'Tazón de frambuesas con yogurt y miel',
    description: 'Antioxidantes de frambuesa chilena + proteína láctea. Bajo en grasa, alto en vitamina C.',
    moment: 'preWorkout',
    focus: ['maintenance', 'recovery'],
    carbs: 38, protein: 14, fat: 3, kcal: 250,
    portion: '100g frambuesas + 150g yogurt + 1 cdita miel',
  }),
  buildFood({
    name: 'Quesillo con pan integral y tomate',
    description: 'Calcio y proteína del quesillo fresco con carbohidratos de pan integral. Ideal para mornings.',
    moment: 'preWorkout',
    focus: ['energy availability', 'performance + recovery'],
    carbs: 36, protein: 16, fat: 8, kcal: 290,
    portion: '60g quesillo + 2 rebanadas pan integral',
  }),
  buildFood({
    name: 'Cereal de maíz con leche y plátano',
    description: 'Carbohidratos rápidos con potasio del plátano. Pre-entreno de carga alta cuando el tiempo es corto.',
    moment: 'preWorkout',
    focus: ['energy availability'],
    carbs: 55, protein: 8, fat: 4, kcal: 290,
    portion: '1 taza cereal + 200ml leche + 1/2 plátano',
  }),
  buildFood({
    name: 'Hummus con pan pita integral',
    description: 'Garbanzos triturados con aceite de oliva: proteína vegetal, fibra y grasas anti-inflamatorias.',
    moment: 'preWorkout',
    focus: ['energy availability', 'recovery'],
    carbs: 35, protein: 10, fat: 8, kcal: 260,
    portion: '3 cdas hummus + 1 pan pita',
  }),
  buildFood({
    name: 'Empanada de pino al horno (mediana)',
    description: 'Clásico chileno horneado: carbohidratos, proteína y hierro del vacuno. Ideal 2 hs antes de sesión.',
    moment: 'preWorkout',
    focus: ['energy availability', 'performance + recovery'],
    carbs: 48, protein: 18, fat: 12, kcal: 410,
    portion: '1 empanada mediana',
  }),
  buildFood({
    name: 'Panqueques de avena con miel y canela',
    description: 'Panqueques sin harina blanca: avena molida, carbohidratos complejos y bajo índice glucémico.',
    moment: 'preWorkout',
    focus: ['energy availability', 'maintenance'],
    carbs: 48, protein: 10, fat: 6, kcal: 300,
    portion: '2 panqueques medianos + 1 cda miel',
  }),
  buildFood({
    name: 'Wrap integral con pechuga y pepino',
    description: 'Tortilla integral con pollo magro y verduras frescas. Macros limpios para pre-entreno vespertino.',
    moment: 'preWorkout',
    focus: ['performance + recovery', 'maintenance'],
    carbs: 40, protein: 24, fat: 6, kcal: 320,
    portion: '1 wrap mediano',
  }),

  // ============================================================
  // INTRA-WORKOUT (16 items)
  // ============================================================

  buildFood({
    name: 'Geles isotónicos Fogg + agua con sal',
    description: 'Hidratos rápidos con electrolitos. Formulación para mantener rendimiento en sesiones de alta intensidad.',
    moment: 'intraWorkout',
    focus: ['energy availability', 'performance + recovery'],
    carbs: 28, protein: 0, fat: 0, kcal: 110,
    portion: '1 gel + 500 ml bebida isotónica',
  }),
  buildFood({
    name: 'Pan amasado con manjar y plátano',
    description: 'Recarga dulce para sesiones largas de ciclismo. Pan con potasio del plátano para prevenir calambres.',
    moment: 'intraWorkout',
    focus: ['energy availability', 'maintenance'],
    carbs: 50, protein: 6, fat: 12, kcal: 420,
    portion: '1 pan pequeño con 1 cda de manjar + 1/2 plátano',
  }),
  buildFood({
    name: 'Dátiles con sal de mar',
    description: 'Azúcares naturales, sodio y antioxidantes naturales. Múltiple cobertura de fueles intra-sesión.',
    moment: 'intraWorkout',
    focus: ['energy availability', 'performance + recovery', 'recovery'],
    carbs: 45, protein: 1, fat: 0, kcal: 180,
    portion: '6-8 dátiles (~60g)',
  }),
  buildFood({
    name: 'Bebida isotónica casera (agua, azúcar, sal, limón)',
    description: 'Electrolitos y carbohidratos simples para rehidratación y energía durante la sesión.',
    moment: 'intraWorkout',
    focus: ['energy availability', 'maintenance'],
    carbs: 30, protein: 0, fat: 0, kcal: 120,
    portion: '500 ml',
  }),
  buildFood({
    name: 'Plátano entero con pizca de sal',
    description: 'Carbohidratos naturales y potasio para prevenir calambres en sesiones largas.',
    moment: 'intraWorkout',
    focus: ['energy availability', 'maintenance', 'recovery'],
    carbs: 27, protein: 1, fat: 0, kcal: 115,
    portion: '1 plátano mediano',
  }),
  buildFood({
    name: 'Galletas de arroz con manjar',
    description: 'Fácil digestión con carbohidratos rápidos. Bajo en fibra, ideal para no generar molestias GI.',
    moment: 'intraWorkout',
    focus: ['energy availability', 'performance + recovery', 'maintenance'],
    carbs: 38, protein: 3, fat: 6, kcal: 220,
    portion: '4 galletas + 1 cda manjar',
  }),
  buildFood({
    name: 'Barra de cereal artesanal (avena, miel, chía)',
    description: 'Barra casera con avena y miel para energía sostenida. Chía aporta omega-3 anti-inflamatorio.',
    moment: 'intraWorkout',
    focus: ['maintenance', 'performance + recovery', 'recovery'],
    carbs: 32, protein: 5, fat: 8, kcal: 230,
    portion: '1 barra (~50g)',
  }),
  buildFood({
    name: 'Naranja pelada con sal',
    description: 'Vitamina C, fructosa y electrolitos para hidratación natural durante el esfuerzo.',
    moment: 'intraWorkout',
    focus: ['energy availability', 'recovery'],
    carbs: 18, protein: 1, fat: 0, kcal: 80,
    portion: '1 naranja grande',
  }),
  buildFood({
    name: 'Higos secos con sal',
    description: 'Alta densidad de carbohidratos naturales, potasio y calcio. Fácil de transportar en maillot.',
    moment: 'intraWorkout',
    focus: ['energy availability', 'performance + recovery'],
    carbs: 40, protein: 2, fat: 0, kcal: 165,
    portion: '5-6 higos (~60g)',
  }),
  buildFood({
    name: 'Bebida de coco natural',
    description: 'Electrolitos naturales (potasio, sodio, magnesio) sin azúcar agregada. Hidratación isotónica real.',
    moment: 'intraWorkout',
    focus: ['energy availability', 'recovery', 'maintenance'],
    carbs: 22, protein: 1, fat: 1, kcal: 100,
    portion: '350 ml',
  }),
  buildFood({
    name: 'Ciruelas deshidratadas',
    description: 'Carbohidratos de rápida absorción con sorbitol. Energía rápida y apoyo digestivo en esfuerzos largos.',
    moment: 'intraWorkout',
    focus: ['energy availability'],
    carbs: 42, protein: 2, fat: 0, kcal: 180,
    portion: '6-7 ciruelas (~60g)',
  }),
  buildFood({
    name: 'Galletas de avena con pasas',
    description: 'Avena + fruta seca: índice glucémico moderado para mantener glucemia estable en Z2 prolongado.',
    moment: 'intraWorkout',
    focus: ['energy availability', 'maintenance'],
    carbs: 38, protein: 4, fat: 7, kcal: 230,
    portion: '3-4 galletas (~50g)',
  }),
  buildFood({
    name: 'Jugo de naranja con sal',
    description: 'Fructosa + glucosa + sodio, sin fibra. Absorción muy rápida, ideal en sprints o intervalos.',
    moment: 'intraWorkout',
    focus: ['energy availability', 'performance + recovery'],
    carbs: 28, protein: 1, fat: 0, kcal: 120,
    portion: '250 ml',
  }),
  buildFood({
    name: 'Rollitos de arroz con palta y sal',
    description: 'Bolitas de arroz blanco envueltas en alga nori. Carbohidratos fáciles de comer pedaleando.',
    moment: 'intraWorkout',
    focus: ['energy availability', 'maintenance'],
    carbs: 45, protein: 3, fat: 4, kcal: 230,
    portion: '2-3 rollitos (~70g)',
  }),
  buildFood({
    name: 'Mix de uvas y nueces en bolsa',
    description: 'Mezcla de uvas frescas (glucosa) y nueces (grasas). Combo para sesiones de duración media a alta.',
    moment: 'intraWorkout',
    focus: ['energy availability', 'performance + recovery'],
    carbs: 30, protein: 4, fat: 10, kcal: 230,
    portion: '100g uvas + 15g nueces',
  }),
  buildFood({
    name: 'Agua de arroz con miel y limón',
    description: 'Bebida de recuperación intra: almidón de arroz hidrolizado, miel y electrolitos cítricos.',
    moment: 'intraWorkout',
    focus: ['energy availability', 'recovery'],
    carbs: 32, protein: 1, fat: 0, kcal: 130,
    portion: '400 ml',
  }),

  // ============================================================
  // POST-WORKOUT (22 items)
  // ============================================================

  buildFood({
    name: 'Charquicán con huevos y ensalada chilena',
    description: 'Plato chileno completo. Carbs, proteína y verduras frescas para post-entreno con macros balanceados.',
    moment: 'postWorkout',
    focus: ['performance + recovery', 'maintenance'],
    carbs: 65, protein: 24, fat: 10, kcal: 520,
    portion: '1 plato mediano',
  }),
  buildFood({
    name: 'Batido de lúcuma, yogurt y quinoa inflada',
    description: 'Recuperación con proteína y glucógeno reconociendo sabores chilenos.',
    moment: 'postWorkout',
    focus: ['recovery'],
    carbs: 40, protein: 28, fat: 4, kcal: 380,
    portion: '400 ml',
  }),
  buildFood({
    name: 'Parfait de yogurt natural, frutos rojos y chía',
    description: 'Snack de recuperación suave. Frutos rojos aportan antioxidantes, chía omega-3 anti-inflamatorio.',
    moment: 'postWorkout',
    focus: ['maintenance', 'recovery'],
    carbs: 36, protein: 12, fat: 7, kcal: 320,
    portion: '200 g',
  }),
  buildFood({
    name: 'Arroz integral con pechuga de pollo asada',
    description: 'Reposición de glucógeno y proteína magra para recuperación completa post-entreno intenso.',
    moment: 'postWorkout',
    focus: ['energy availability', 'performance + recovery'],
    carbs: 55, protein: 35, fat: 5, kcal: 420,
    portion: '1 taza arroz cocido + 150g pollo',
  }),
  buildFood({
    name: 'Lentejas con arroz y huevo duro',
    description: 'Legumbres chilenas con arroz: proteína completa vegetal y carbohidratos de digestión lenta.',
    moment: 'postWorkout',
    focus: ['performance + recovery', 'recovery'],
    carbs: 65, protein: 28, fat: 6, kcal: 450,
    portion: '1 plato mediano',
  }),
  buildFood({
    name: 'Batido de proteína con leche y plátano',
    description: 'Proteína de absorción rápida con carbohidratos para ventana anabólica post-entreno.',
    moment: 'postWorkout',
    focus: ['performance + recovery'],
    carbs: 40, protein: 30, fat: 4, kcal: 320,
    portion: '400 ml',
  }),
  buildFood({
    name: 'Pasta con salsa de tomate y atún',
    description: 'Pasta con proteína marina para reposición de glucógeno tras sesión larga.',
    moment: 'postWorkout',
    focus: ['energy availability'],
    carbs: 68, protein: 30, fat: 7, kcal: 470,
    portion: '1 plato mediano',
  }),
  buildFood({
    name: 'Ensalada de quinoa con pollo y palta',
    description: 'Bowl de recuperación completo con proteína, carbohidratos complejos y grasas anti-inflamatorias.',
    moment: 'postWorkout',
    focus: ['performance + recovery', 'recovery'],
    carbs: 38, protein: 30, fat: 14, kcal: 430,
    portion: '1 bowl',
  }),
  buildFood({
    name: 'Marraqueta tostada con requesón y mermelada',
    description: 'Carbohidratos rápidos más proteína láctea. Macros balanceados, fácil digestión post-entreno.',
    moment: 'postWorkout',
    focus: ['energy availability', 'maintenance', 'performance + recovery'],
    carbs: 48, protein: 12, fat: 4, kcal: 290,
    portion: '2 rebanadas',
  }),
  buildFood({
    name: 'Porotos con rienda',
    description: 'Plato tradicional chileno: legumbres, fideos y proteína para recuperación calórica completa.',
    moment: 'postWorkout',
    focus: ['energy availability', 'maintenance', 'performance + recovery'],
    carbs: 70, protein: 22, fat: 8, kcal: 460,
    portion: '1 plato mediano',
  }),
  buildFood({
    name: 'Huevos revueltos con pan integral y palta',
    description: 'Proteína completa del huevo + carbohidratos de pan integral + grasas mono del palta.',
    moment: 'postWorkout',
    focus: ['performance + recovery', 'recovery'],
    carbs: 35, protein: 22, fat: 14, kcal: 380,
    portion: '3 huevos + 2 rebanadas pan + 1/4 palta',
  }),
  buildFood({
    name: 'Pollo a la plancha con puré de papas',
    description: 'Proteína magra con carbohidratos de papa. Macros clásicos de recuperación post-entreno de fuerza.',
    moment: 'postWorkout',
    focus: ['performance + recovery', 'energy availability'],
    carbs: 45, protein: 35, fat: 8, kcal: 410,
    portion: '150g pollo + 1 taza puré',
  }),
  buildFood({
    name: 'Tortilla española (huevo y papa)',
    description: 'Proteína del huevo con carbohidratos de papa. Plato español-chileno popular post-entrenamiento.',
    moment: 'postWorkout',
    focus: ['energy availability', 'performance + recovery'],
    carbs: 32, protein: 20, fat: 16, kcal: 360,
    portion: '2 porciones medianas',
  }),
  buildFood({
    name: 'Congrio frito con arroz blanco',
    description: 'Pescado chileno con alto contenido proteico y arroz para reposición de glucógeno.',
    moment: 'postWorkout',
    focus: ['performance + recovery', 'energy availability'],
    carbs: 48, protein: 32, fat: 12, kcal: 440,
    portion: '150g congrio + 1 taza arroz',
  }),
  buildFood({
    name: 'Guiso de lentejas con tocino ahumado',
    description: 'Legumbres con proteína completa y sodio del tocino para reposición de electrolitos tras sesión intensa.',
    moment: 'postWorkout',
    focus: ['energy availability', 'performance + recovery'],
    carbs: 60, protein: 24, fat: 10, kcal: 450,
    portion: '1 plato mediano',
  }),
  buildFood({
    name: 'Batido verde (espinaca, plátano, avena y leche)',
    description: 'Hierro de espinaca, potasio del plátano y proteína de leche. Batido completo de recuperación.',
    moment: 'postWorkout',
    focus: ['recovery', 'maintenance'],
    carbs: 45, protein: 14, fat: 4, kcal: 280,
    portion: '400 ml',
  }),
  buildFood({
    name: 'Wrap de pavo y quinoa con verduras',
    description: 'Tortilla integral con pavo magro y quinoa: proteína + carbohidratos complejos en formato portátil.',
    moment: 'postWorkout',
    focus: ['performance + recovery', 'maintenance'],
    carbs: 42, protein: 28, fat: 8, kcal: 380,
    portion: '1 wrap mediano',
  }),
  buildFood({
    name: 'Fideos con salsa bolognesa y queso rallado',
    description: 'Pasta italiana con carne y queso: carbohidratos, proteína y calcio para recuperación de alta carga.',
    moment: 'postWorkout',
    focus: ['energy availability', 'performance + recovery'],
    carbs: 65, protein: 25, fat: 14, kcal: 490,
    portion: '1 plato mediano',
  }),
  buildFood({
    name: 'Estofado de vacuno con papas y zanahoria',
    description: 'Hierro hemínico del vacuno + almidón resistente de papa. Recuperación completa en invierno.',
    moment: 'postWorkout',
    focus: ['recovery', 'performance + recovery'],
    carbs: 48, protein: 28, fat: 10, kcal: 420,
    portion: '1 plato mediano',
  }),
  buildFood({
    name: 'Bowl de açaí con granola y plátano',
    description: 'Antioxidantes de açaí + carbohidratos de granola y plátano. Recuperación anti-inflamatoria.',
    moment: 'postWorkout',
    focus: ['recovery', 'maintenance'],
    carbs: 55, protein: 8, fat: 8, kcal: 350,
    portion: '1 bowl',
  }),
  buildFood({
    name: 'Salmón a la plancha con puré de camote',
    description: 'Omega-3 anti-inflamatorio + beta-caroteno del camote. Post-entreno de alta calidad nutricional.',
    moment: 'postWorkout',
    focus: ['recovery', 'performance + recovery'],
    carbs: 42, protein: 32, fat: 16, kcal: 440,
    portion: '150g salmón + 1 taza puré camote',
  }),
  buildFood({
    name: 'Tostadas con atún y palta',
    description: 'Proteína marina + grasas saludables en formato rápido. Ideal post-entreno de fuerza o swim.',
    moment: 'postWorkout',
    focus: ['recovery', 'performance + recovery', 'maintenance'],
    carbs: 30, protein: 26, fat: 14, kcal: 360,
    portion: '2 tostadas + 1 lata atún + 1/4 palta',
  }),

  // ============================================================
  // SNACK (20 items)
  // ============================================================

  buildFood({
    name: 'Yogurt natural con avena, berries y chía',
    description: 'Snack con proteína, antioxidantes y omega-3. Ratio CHO:PRO apto para recuperación activa.',
    moment: 'snack',
    focus: ['maintenance', 'performance + recovery', 'recovery'],
    carbs: 36, protein: 14, fat: 8, kcal: 320,
    portion: '1 bowl',
  }),
  buildFood({
    name: 'Palta rellena con garbanzos y tomate',
    description: 'Snack salado, rico en grasas buenas y proteína vegetal para antes de dormir o entre sesiones.',
    moment: 'snack',
    focus: ['maintenance', 'recovery'],
    carbs: 22, protein: 9, fat: 18, kcal: 310,
    portion: '1 palta grande',
  }),
  buildFood({
    name: 'Marraqueta con mantequilla de maní y plátano',
    description: 'Snack energético chileno con carbohidratos, grasas y proteína. Ideal en días de carga alta.',
    moment: 'snack',
    focus: ['energy availability', 'performance + recovery'],
    carbs: 42, protein: 10, fat: 12, kcal: 330,
    portion: '1/2 marraqueta + 1 cda mantequilla de maní + 1/2 plátano',
  }),
  buildFood({
    name: 'Nueces con pasas y dátiles',
    description: 'Grasas saludables, azúcares naturales y antioxidantes. Snack calórico para días de entrenamiento.',
    moment: 'snack',
    focus: ['energy availability', 'performance + recovery', 'recovery'],
    carbs: 32, protein: 5, fat: 18, kcal: 320,
    portion: '30g nueces + 20g fruta seca',
  }),
  buildFood({
    name: 'Huevos duros con galletas de arroz',
    description: 'Proteína completa con carbohidratos de fácil digestión para recuperación entre sesiones.',
    moment: 'snack',
    focus: ['performance + recovery', 'maintenance'],
    carbs: 20, protein: 16, fat: 10, kcal: 240,
    portion: '2 huevos + 2 galletas de arroz',
  }),
  buildFood({
    name: 'Manzana con mantequilla de maní',
    description: 'Fruta chilena con grasas y proteína. Carbohidratos de fruta para recarga rápida y mantenimiento.',
    moment: 'snack',
    focus: ['maintenance', 'energy availability'],
    carbs: 25, protein: 6, fat: 10, kcal: 220,
    portion: '1 manzana + 1 cda mantequilla de maní',
  }),
  buildFood({
    name: 'Batido de lúcuma con leche',
    description: 'Batido suave con lúcuma chilena, carbohidratos y calcio para recuperación entre sesiones.',
    moment: 'snack',
    focus: ['maintenance', 'recovery'],
    carbs: 36, protein: 10, fat: 4, kcal: 240,
    portion: '350 ml',
  }),
  buildFood({
    name: 'Tuna en lata con galletas de arroz',
    description: 'Proteína marina de alto valor biológico con carbohidratos simples para recuperación activa.',
    moment: 'snack',
    focus: ['performance + recovery', 'recovery'],
    carbs: 16, protein: 22, fat: 3, kcal: 190,
    portion: '1 lata (80g) + 4 galletas de arroz',
  }),
  buildFood({
    name: 'Maní tostado salado',
    description: 'Proteína vegetal, grasas insaturadas y potasio. Snack calórico denso para días de carga alta.',
    moment: 'snack',
    focus: ['energy availability', 'maintenance', 'performance + recovery'],
    carbs: 12, protein: 12, fat: 18, kcal: 260,
    portion: '40g',
  }),
  buildFood({
    name: 'Kefir con chía y fresas',
    description: 'Probióticos del kefir + antioxidantes de fresa + omega-3 de chía. Snack anti-inflamatorio.',
    moment: 'snack',
    focus: ['recovery', 'maintenance'],
    carbs: 18, protein: 12, fat: 4, kcal: 180,
    portion: '200ml kefir + 1 cda chía + 80g fresas',
  }),
  buildFood({
    name: 'Palitos de zanahoria con hummus',
    description: 'Beta-caroteno + proteína vegetal + fibra. Snack saciante y bajo en calorías.',
    moment: 'snack',
    focus: ['maintenance', 'recovery'],
    carbs: 18, protein: 6, fat: 8, kcal: 200,
    portion: '100g zanahoria + 3 cdas hummus',
  }),
  buildFood({
    name: 'Pan de centeno con quesillo fresco',
    description: 'Pan de centeno integral con quesillo: fibra, proteína y carbohidratos de bajo índice glucémico.',
    moment: 'snack',
    focus: ['maintenance', 'performance + recovery'],
    carbs: 30, protein: 14, fat: 6, kcal: 240,
    portion: '2 rebanadas + 60g quesillo',
  }),
  buildFood({
    name: 'Uvas con almendras',
    description: 'Glucosa natural de uva chilena con proteína y grasas de almendra. Snack equilibrado y portátil.',
    moment: 'snack',
    focus: ['energy availability', 'maintenance'],
    carbs: 25, protein: 5, fat: 12, kcal: 240,
    portion: '100g uvas + 20g almendras',
  }),
  buildFood({
    name: 'Requesón con mermelada de ciruela',
    description: 'Proteína láctea baja en grasa con fruta local de temporada. Snack post-almuerzo o pre-noche.',
    moment: 'snack',
    focus: ['maintenance', 'recovery'],
    carbs: 22, protein: 16, fat: 4, kcal: 200,
    portion: '100g requesón + 1 cda mermelada',
  }),
  buildFood({
    name: 'Edamame con sal de mar',
    description: 'Soja verde: proteína completa vegetal, fibra y fitoestrógenos. Snack salado anti-inflamatorio.',
    moment: 'snack',
    focus: ['recovery', 'maintenance', 'performance + recovery'],
    carbs: 14, protein: 12, fat: 5, kcal: 150,
    portion: '100g edamame cocido',
  }),
  buildFood({
    name: 'Panqueque de avena con plátano',
    description: 'Panqueque sin gluten hecho solo con avena y plátano: carbohidratos naturales y potasio.',
    moment: 'snack',
    focus: ['energy availability', 'maintenance'],
    carbs: 38, protein: 10, fat: 6, kcal: 250,
    portion: '2 panqueques',
  }),
  buildFood({
    name: 'Mix de semillas (zapallo, girasol, chía)',
    description: 'Zinc, magnesio y omega-3 de semillas crudas. Micronutrientes clave para recuperación muscular.',
    moment: 'snack',
    focus: ['recovery', 'maintenance'],
    carbs: 12, protein: 10, fat: 18, kcal: 260,
    portion: '30g mix semillas',
  }),
  buildFood({
    name: 'Tostadas de centeno con salmón ahumado',
    description: 'Omega-3 del salmón ahumado con carbohidratos de centeno. Snack premium de recuperación.',
    moment: 'snack',
    focus: ['recovery', 'performance + recovery'],
    carbs: 28, protein: 18, fat: 10, kcal: 290,
    portion: '2 tostadas + 50g salmón ahumado',
  }),
  buildFood({
    name: 'Dátiles rellenos con almendra y coco',
    description: 'Energía concentrada, potasio y grasas saludables. Snack dulce natural pre-sesión vespertina.',
    moment: 'snack',
    focus: ['energy availability', 'performance + recovery'],
    carbs: 35, protein: 4, fat: 8, kcal: 230,
    portion: '4 dátiles rellenos',
  }),
  buildFood({
    name: 'Cottage con piña y miel',
    description: 'Proteína caseína de lenta absorción + glucosa de piña. Snack ideal antes de dormir.',
    moment: 'snack',
    focus: ['recovery', 'maintenance'],
    carbs: 24, protein: 18, fat: 3, kcal: 200,
    portion: '150g cottage + 80g piña + 1 cdita miel',
  }),

  // ============================================================
  // DINNER (22 items)
  // ============================================================

  buildFood({
    name: 'Cazuela de vacuno con camote',
    description: 'Proteína magra, camote y verduras para recuperar la noche. Ratio CHO:PRO 1.7:1 para alto rendimiento.',
    moment: 'dinner',
    focus: ['recovery', 'maintenance', 'performance + recovery'],
    carbs: 54, protein: 32, fat: 8, kcal: 460,
    portion: '1 plato profundo',
  }),
  buildFood({
    name: 'Salmón a la plancha con quínoa y salsa de merkén',
    description: 'Omega-3 anti-inflamatorio, proteína completa y quínoa. Ratio CHO:PRO ideal para recuperación.',
    moment: 'dinner',
    focus: ['recovery', 'performance + recovery'],
    carbs: 36, protein: 34, fat: 18, kcal: 510,
    portion: '150 g salmón + 1/2 taza quínoa',
  }),
  buildFood({
    name: 'Cazuela de pollo con arroz y verduras',
    description: 'Cena completa chilena con proteína magra, carbohidratos y micronutrientes de verduras de estación.',
    moment: 'dinner',
    focus: ['energy availability', 'recovery'],
    carbs: 60, protein: 30, fat: 6, kcal: 440,
    portion: '1 plato profundo',
  }),
  buildFood({
    name: 'Fideos con pesto de albahaca y pechuga',
    description: 'Pasta con proteína y aceite de oliva. Macros balanceados para cenas de alta carga y mantenimiento.',
    moment: 'dinner',
    focus: ['energy availability', 'performance + recovery', 'maintenance'],
    carbs: 62, protein: 28, fat: 16, kcal: 520,
    portion: '1 plato mediano',
  }),
  buildFood({
    name: 'Reineta al vapor con puré de papas',
    description: 'Pescado blanco chileno bajo en grasa con puré para cenas de recuperación ligera.',
    moment: 'dinner',
    focus: ['performance + recovery', 'recovery'],
    carbs: 45, protein: 30, fat: 8, kcal: 380,
    portion: '150g pescado + 1 taza puré',
  }),
  buildFood({
    name: 'Porotos granados con choclo y albahaca',
    description: 'Plato vegetariano de verano chileno: legumbres con maíz, proteína vegetal y carbohidratos complejos.',
    moment: 'dinner',
    focus: ['energy availability', 'maintenance', 'performance + recovery'],
    carbs: 65, protein: 20, fat: 4, kcal: 400,
    portion: '1 plato',
  }),
  buildFood({
    name: 'Ensalada de garbanzos con espinaca y huevo',
    description: 'Proteína vegetal completa, hierro, vitamina K. Cena ligera con macros balanceados para mantenimiento.',
    moment: 'dinner',
    focus: ['maintenance', 'recovery', 'performance + recovery'],
    carbs: 32, protein: 22, fat: 12, kcal: 350,
    portion: '1 bowl grande',
  }),
  buildFood({
    name: 'Sopaipillas pasadas (versión ligera)',
    description: 'Cena tradicional chilena de invierno con carbohidratos de zapallo para reposición en días de carga alta.',
    moment: 'dinner',
    focus: ['energy availability'],
    carbs: 55, protein: 5, fat: 8, kcal: 320,
    portion: '3 sopaipillas medianas',
  }),
  buildFood({
    name: 'Pastel de papas con vacuno molido',
    description: 'Clásico chileno con carne magra y papa: proteína + hierro + carbohidratos en cena de invierno.',
    moment: 'dinner',
    focus: ['energy availability', 'performance + recovery'],
    carbs: 52, protein: 28, fat: 12, kcal: 450,
    portion: '1 porción mediana',
  }),
  buildFood({
    name: 'Albóndigas de pavo con salsa de tomate y arroz',
    description: 'Pavo magro con tomates naturales: proteína baja en grasa y licopeno anti-inflamatorio.',
    moment: 'dinner',
    focus: ['recovery', 'performance + recovery'],
    carbs: 55, protein: 32, fat: 8, kcal: 440,
    portion: '4 albóndigas + 1 taza arroz',
  }),
  buildFood({
    name: 'Estofado de pollo con zapallo y papas',
    description: 'Vitamina A del zapallo + proteína de pollo + almidón de papa. Cena completa chilena.',
    moment: 'dinner',
    focus: ['recovery', 'maintenance'],
    carbs: 48, protein: 28, fat: 8, kcal: 400,
    portion: '1 plato mediano',
  }),
  buildFood({
    name: 'Congrio al horno con limón y verduras asadas',
    description: 'Pescado chileno magro al horno: alta proteína, bajo en grasa, con verduras de bajo índice glucémico.',
    moment: 'dinner',
    focus: ['recovery', 'maintenance'],
    carbs: 20, protein: 34, fat: 10, kcal: 330,
    portion: '180g congrio + 150g verduras',
  }),
  buildFood({
    name: 'Pasta primavera con verduras y aceite de oliva',
    description: 'Carbohidratos de pasta + verduras de estación + grasa mono del aceite. Cena de carga alta.',
    moment: 'dinner',
    focus: ['energy availability', 'maintenance'],
    carbs: 65, protein: 14, fat: 12, kcal: 450,
    portion: '1 plato mediano',
  }),
  buildFood({
    name: 'Curry de garbanzos con arroz basmati',
    description: 'Cúrcuma anti-inflamatoria + proteína vegetal de garbanzo + arroz de bajo índice glucémico.',
    moment: 'dinner',
    focus: ['recovery', 'energy availability', 'maintenance'],
    carbs: 68, protein: 18, fat: 10, kcal: 460,
    portion: '1 plato mediano',
  }),
  buildFood({
    name: 'Revuelto gramajo (papas, huevo, jamón)',
    description: 'Proteína completa del huevo con jamón y papa: cena rápida de recuperación post-sesión nocturna.',
    moment: 'dinner',
    focus: ['energy availability', 'performance + recovery'],
    carbs: 40, protein: 22, fat: 14, kcal: 390,
    portion: '1 plato mediano',
  }),
  buildFood({
    name: 'Merluza al vapor con papas y zanahoria',
    description: 'Pescado blanco chileno muy bajo en grasa. Cena liviana de recuperación activa post-carrera.',
    moment: 'dinner',
    focus: ['recovery', 'maintenance'],
    carbs: 35, protein: 28, fat: 5, kcal: 320,
    portion: '160g merluza + 150g papas cocidas',
  }),
  buildFood({
    name: 'Guiso de arvejas con carne magra',
    description: 'Arvejas chilenas con carne: fibra, hierro y proteína completa. Cena invernal de mantenimiento.',
    moment: 'dinner',
    focus: ['maintenance', 'recovery', 'performance + recovery'],
    carbs: 50, protein: 24, fat: 8, kcal: 390,
    portion: '1 plato mediano',
  }),
  buildFood({
    name: 'Wrap integral con atún y ensalada',
    description: 'Tortilla integral con atún en agua: proteína baja en grasa, cena ligera antes de dormir.',
    moment: 'dinner',
    focus: ['recovery', 'maintenance'],
    carbs: 38, protein: 28, fat: 8, kcal: 360,
    portion: '1 wrap mediano',
  }),
  buildFood({
    name: 'Sopa de tomate casera con tostadas integrales',
    description: 'Licopeno de tomate cocido + carbohidratos de tostada. Cena liviana con antioxidantes.',
    moment: 'dinner',
    focus: ['maintenance', 'recovery'],
    carbs: 35, protein: 8, fat: 6, kcal: 250,
    portion: '1 tazón sopa + 2 tostadas',
  }),
  buildFood({
    name: 'Humitas de choclo con ensalada mixta',
    description: 'Masa de maíz chilena al vapor con verduras: carbohidratos naturales y vitaminas del maíz fresco.',
    moment: 'dinner',
    focus: ['energy availability', 'maintenance'],
    carbs: 48, protein: 10, fat: 8, kcal: 320,
    portion: '2 humitas + ensalada',
  }),
  buildFood({
    name: 'Pollo al horno con quínoa y brócoli',
    description: 'Proteína magra + carbohidratos complejos de quínoa + sulforafano anti-cáncer del brócoli.',
    moment: 'dinner',
    focus: ['recovery', 'performance + recovery'],
    carbs: 38, protein: 36, fat: 8, kcal: 390,
    portion: '150g pollo + 1/2 taza quínoa + 100g brócoli',
  }),
  buildFood({
    name: 'Lentejas rojas con espinaca y curcuma',
    description: 'Legumbres de cocción rápida con espinaca y cúrcuma: hierro + anti-inflamatorio + proteína vegetal.',
    moment: 'dinner',
    focus: ['recovery', 'maintenance', 'performance + recovery'],
    carbs: 56, protein: 22, fat: 4, kcal: 360,
    portion: '1 plato mediano',
  }),
  buildFood({
    name: 'Filete de vacuno magro con camote asado',
    description: 'Hierro hemínico + vitamina A del camote + proteína de alta calidad. Cena de alta carga.',
    moment: 'dinner',
    focus: ['performance + recovery', 'energy availability'],
    carbs: 42, protein: 36, fat: 10, kcal: 420,
    portion: '150g filete + 1 camote mediano',
  }),
];

// Coverage validation (development only)
if (process.env.NODE_ENV === 'development') {
  const moments: FoodMoment[] = ['preWorkout', 'intraWorkout', 'postWorkout', 'snack', 'dinner'];
  const focuses = ['energy availability', 'performance + recovery', 'maintenance', 'recovery'];
  for (const m of moments) {
    for (const f of focuses) {
      const count = foodCatalog.filter(item => item.moment === m && item.focus.includes(f)).length;
      if (count < 4) {
        console.warn(`[catalog] COVERAGE GAP: ${m} × ${f} has ${count} items (need >=4)`);
      }
    }
  }
}
